use birds;
insert into type_names(type_name, type_description) values ('Procellariiformes', 'Albatrosses and Petrels');
insert into type_names(type_name, type_description) values ('Falconiformes', 'Birds of Prey');
insert into type_names(type_name, type_description) values ('Turniciformes', 'Buttonquails');
insert into type_names(type_name, type_description) values ('Casuariiformes', 'Cassowaries and Emus');
insert into type_names(type_name, type_description) values ('Gruiformes', 'Cranes, Coots, and Rails');
insert into type_names(type_name, type_description) values ('Cuculiformes', 'Cuckoos and Turacos');
insert into type_names(type_name, type_description) values ('Phoenicopteriformes', 'Flamingos');
insert into type_names(type_name, type_description) values ('Galliformes', 'Game Birds');
insert into type_names(type_name, type_description) values ('Podicipediformes', 'Grebes');
insert into type_names(type_name, type_description) values ('Ciconiiformes', 'Herons and Storks');
insert into type_names(type_name, type_description) values ('Apodiformes', 'Hummingbirds and Swifts');
insert into type_names(type_name, type_description) values ('Coraciiformes', 'Kingfishers');
insert into type_names(type_name, type_description) values ('Apterygiformes', 'Kiwis');
insert into type_names(type_name, type_description) values ('Gaviiformes', 'Loons');
insert into type_names(type_name, type_description) values ('Coliiformes', 'Mousebirds');
insert into type_names(type_name, type_description) values ('Caprimulgiformes', 'Nightjars and Frogmouths');
insert into type_names(type_name, type_description) values ('Struthioniformes', 'The Ostrich');
insert into type_names(type_name, type_description) values ('Strigiformes', 'Owls');
insert into type_names(type_name, type_description) values ('Psittaciformes', 'Parrots and Cockatoos');
insert into type_names(type_name, type_description) values ('Pelecaniformes', 'Pelicans, Cormorants, and Frigatebirds');
insert into type_names(type_name, type_description) values ('Sphenisciformes', 'Penguins');
insert into type_names(type_name, type_description) values ('Passeriformes', 'Perching Birds');
insert into type_names(type_name, type_description) values ('Columbiformes', 'Pigeons and Doves');
insert into type_names(type_name, type_description) values ('Rheiformes', 'Rheas');
insert into type_names(type_name, type_description) values ('Pteroclidiformes', 'Sandgrouses');
insert into type_names(type_name, type_description) values ('Charadriiformes', 'Shorebirds');
insert into type_names(type_name, type_description) values ('Tinamiformes', 'Tinamous');
insert into type_names(type_name, type_description) values ('Trogoniformes', 'Trogons and Quetzals');
insert into type_names(type_name, type_description) values ('Anseriformes', 'Waterfowl');
insert into type_names(type_name, type_description) values ('Piciformes', 'Woodpeckers and Toucans');